name: Build ExecuTorch (android-26, arm64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_NDK_VERSION: 25.2.9519653
      ANDROID_API: 26
      ANDROID_ABIS: 'arm64-v8a'
      EXECUTORCH_CMAKE_BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake ninja-build python3 wget unzip curl jq

      - name: Install Android SDK/NDK
        run: |
          mkdir -p "$ANDROID_SDK_ROOT"
          cd "$ANDROID_SDK_ROOT"
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platforms;android-${ANDROID_API}" \
            "build-tools;34.0.0" \
            "cmake;3.22.1" \
            "ndk;${ANDROID_NDK_VERSION}"
          echo "ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_ENV
          echo "ANDROID_SDK=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

      - name: Install buck2 (latest)
        run: |
          set -euo pipefail
          sudo apt-get update && sudo apt-get install -y zstd coreutils file
          TAG="latest"
          ASSET="buck2-x86_64-unknown-linux-gnu.zst"  # ubuntu-latest は x86_64 です
          URL="https://github.com/facebook/buck2/releases/download/${TAG}/${ASSET}"
      
          curl -fL --retry 3 -o /tmp/buck2.zst "$URL" || { echo "ERROR: Failed to download $URL"; exit 1; }
          [ -s /tmp/buck2.zst ] || { echo "ERROR: Downloaded file is empty."; exit 1; }
      
          zstd -d /tmp/buck2.zst -o /tmp/buck2 || { echo "ERROR: Failed to decompress buck2.zst"; exit 1; }
          [ -s /tmp/buck2 ] || { echo "ERROR: Decompressed buck2 is empty."; exit 1; }
          file /tmp/buck2 | grep -q "ELF" || { echo "ERROR: buck2 is not an ELF binary."; exit 1; }
      
          sudo install -m 0755 /tmp/buck2 /usr/local/bin/buck2
          buck2 --version || { echo "ERROR: buck2 does not run."; exit 1; }

      - name: Enable XNNPACK + PTE flags in script
        run: |
          set -e
          f="scripts/build_android_library.sh"
          grep -q "EXECUTORCH_BUILD_XNNPACK" "$f" || \
            sed -i 's|cmake \. -DCMAKE_INSTALL_PREFIX=\${CMAKE_OUT} |cmake . -DCMAKE_INSTALL_PREFIX=${CMAKE_OUT} -DEXECUTORCH_BUILD_XNNPACK=ON -DEXECUTORCH_BUILD_PTE=ON |' "$f"

      - name: Build via official script
        env:
          PYTHON_EXECUTABLE: python3
        run: |
          set -e
          bash scripts/build_android_library.sh

      - name: Sanity check
        run: |
          set -e
          test -d cmake-out-android-so/arm64-v8a || { echo "ERROR: Missing output directory cmake-out-android-so/arm64-v8a"; exit 1; }
          ls cmake-out-android-so/arm64-v8a/*.so >/dev/null 2>&1 || { echo "ERROR: No .so files produced"; exit 1; }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executorch-android-arm64
          path: cmake-out-android-so/arm64-v8a/*.so
