name: build-executorch-android

on:
  workflow_dispatch:

env:
  EXECUTORCH_VER: v0.7.0
  ANDROID_ABI: arm64-v8a
  ANDROID_API: "26"
  BUILD_TYPE: Release
  PYTORCH_REF: v2.4.0
  CONDA_ENV: executorch-android
  OUTDIR: output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NDK
        id: ndk
        uses: actions/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ${{ env.CONDA_ENV }}
          auto-activate-base: false
          python-version: "3.10"

      - name: Prepare env
        shell: bash
        run: |
          echo "ANDROID_NDK=${{ steps.ndk.outputs.ndk-path }}" >> "$GITHUB_ENV"
          conda install -y -c conda-forge cmake=3.29 ninja git
          python -m pip install -U "pip>=24" "setuptools>=70" "wheel>=0.43" "packaging>=24.2"

      - name: Clone executorch
        shell: bash
        run: |
          if [ ! -d executorch ]; then
            git clone --branch "${EXECUTORCH_VER}" --depth 1 https://github.com/pytorch/executorch.git
            ( cd executorch && git submodule update --init --recursive )
          fi

      - name: Python deps
        shell: bash
        run: |
          ( cd executorch && python -m pip install -r requirements-dev.txt )
          python -m pip install --index-url https://download.pytorch.org/whl/test/cpu torch
          python -m pip install "executorch>=0.7,<0.8"
          export PYTHONPATH="$GITHUB_WORKSPACE/executorch:${PYTHONPATH:-}"
          python -c "import os;print('PYTHONPATH=',os.environ.get('PYTHONPATH'));import executorch,executorch.codegen,torchgen;print('imports OK')"

      - name: Configure
        shell: bash
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE/executorch:${PYTHONPATH:-}"
          cd executorch
          git clean -fdx -e cmake-android-out
          rm -rf cmake-android-out
          cmake -S . -B cmake-android-out \
            -DCMAKE_SYSTEM_NAME=Android \
            -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK}/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI="${ANDROID_ABI}" \
            -DANDROID_PLATFORM=android-${ANDROID_API} \
            -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
            -DCMAKE_INSTALL_PREFIX="$PWD/_install" \
            -DEXECUTORCH_BUILD_EXECUTOR_RUNNER=ON \
            -DEXECUTORCH_BUILD_VULKAN=ON \
            -DEXECUTORCH_BUILD_EXTENSION_DATA_LOADER=ON \
            -DEXECUTORCH_BUILD_EXTENSION_MODULE=ON \
            -DEXECUTORCH_BUILD_EXTENSION_FLAT_TENSOR=ON \
            -DEXECUTORCH_BUILD_EXTENSION_TENSOR=ON \
            -DEXECUTORCH_BUILD_PORTABLE_OPS=ON \
            -DCMAKE_C_FLAGS="-D__ANDROID__=1 -I${PWD}/jni/include" \
            -DCMAKE_CXX_FLAGS="-D__ANDROID__=1 -I${PWD}/jni/include -I${PWD}/.. -I${PWD}"

      - name: Build and Install
        shell: bash
        run: |
          export PATH="$CONDA_PREFIX/bin:$PATH"
          cd executorch
          cmake --build cmake-android-out --target all -j"$(nproc)"
          cmake --install cmake-android-out

      - name: Package headers and libs
        shell: bash
        run: |
          set -euo pipefail
          cd executorch
          INSTALL_PREFIX="${INSTALL_PREFIX:-$PWD/_install}"
          ABI="${ANDROID_ABI:-arm64-v8a}"
          mkdir -p "${OUTDIR}/jni/include" "${OUTDIR}/libs/${ABI}"
          if [ -d "${INSTALL_PREFIX}/include" ]; then
            rsync -a --prune-empty-dirs \
              --include '*/' --include '*.h' --include '*.hpp' --include '*.inc' --exclude '*' \
              "${INSTALL_PREFIX}/include/" "${OUTDIR}/jni/include/"
          fi
          rsync -a --prune-empty-dirs \
            --include '*/' --include '*.h' --include '*.hpp' --include '*.inc' --exclude '*' \
            ./ "${OUTDIR}/jni/include/executorch/"
          mapfile -d '' FILES < <(
            { test -d "${INSTALL_PREFIX}/lib" && find "${INSTALL_PREFIX}/lib" -type f \( -name 'lib*.a' -o -name 'lib*.so' \) -print0; }
            find cmake-android-out -type f \( -name 'lib*.a' -o -name 'lib*.so' \) -print0
          )
          if [ "${#FILES[@]}" -eq 0 ]; then
            echo "ERROR: No libraries found under ${INSTALL_PREFIX}/lib or cmake-android-out." >&2
            exit 1
          fi
          for f in "${FILES[@]}"; do
            cp -f "$f" "${OUTDIR}/libs/${ABI}/"
          done
          echo "Headers: $(realpath "${OUTDIR}/jni/include")"
          echo "Libs: $(realpath "${OUTDIR}/libs/${ABI}")"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executorch-android-${{ env.ANDROID_ABI }}
          path: executorch/${{ env.OUTDIR }}
